import type { Metadata } from 'next';
import './globals.css';
import { UiMantineProvider } from '@repo/ui-mantine/provider';
import { ShadcnThemeProvider } from '@repo/ui-shadcn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ShadcnThemeProvider>{children}</ShadcnThemeProvider>
      </body>
    </html>
  );
}

