import { z } from 'zod';
import type { FormSchema } from './types';

// ─── Employee Form Schema ──────────────────────────────────────────────────────

export const employeeFormSchema: FormSchema = {
  id: 'employee-profile',
  name: 'Employee Profile',
  description: 'Employee information management with role-based access control',
  fields: [
    {
      id: 'firstName',
      label: 'First Name',
      type: 'text',
      required: true,
      placeholder: 'Enter first name',
      permissionRules: [{ roles: ['employee', 'manager', 'admin'], accessLevel: 'editable' }],
      validationSchema: z.string().min(2, 'First name must be at least 2 characters'),
    },
    {
      id: 'lastName',
      label: 'Last Name',
      type: 'text',
      required: true,
      placeholder: 'Enter last name',
      permissionRules: [{ roles: ['employee', 'manager', 'admin'], accessLevel: 'editable' }],
      validationSchema: z.string().min(2, 'Last name must be at least 2 characters'),
    },
    {
      id: 'email',
      label: 'Email',
      type: 'email',
      required: true,
      placeholder: 'employee@company.com',
      permissionRules: [{ roles: ['employee', 'manager', 'admin'], accessLevel: 'readonly' }],
      validationSchema: z.string().email('Invalid email address'),
    },
    {
      id: 'phoneNumber',
      label: 'Phone Number',
      type: 'text',
      placeholder: '+1 (555) 000-0000',
      permissionRules: [{ roles: ['employee', 'manager', 'admin'], accessLevel: 'editable' }],
      validationSchema: z.string().optional(),
      sanitize: (value) => (typeof value === 'string' ? value.replace(/[^\d+\-() ]/g, '') : value),
    },
    {
      id: 'department',
      label: 'Department',
      type: 'select',
      required: true,
      options: [
        { value: 'engineering', label: 'Engineering' },
        { value: 'sales', label: 'Sales' },
        { value: 'marketing', label: 'Marketing' },
        { value: 'hr', label: 'Human Resources' },
        { value: 'finance', label: 'Finance' },
      ],
      permissionRules: [
        { roles: ['employee'], accessLevel: 'readonly' },
        { roles: ['manager', 'admin'], accessLevel: 'editable' },
      ],
      validationSchema: z.enum(['engineering', 'sales', 'marketing', 'hr', 'finance']),
    },
    {
      id: 'jobTitle',
      label: 'Job Title',
      type: 'text',
      required: true,
      placeholder: 'Software Engineer',
      permissionRules: [
        { roles: ['employee'], accessLevel: 'readonly' },
        { roles: ['manager', 'admin'], accessLevel: 'editable' },
      ],
      validationSchema: z.string().min(2, 'Job title is required'),
    },
    {
      id: 'salary',
      label: 'Annual Salary',
      type: 'number',
      placeholder: '75000',
      description: 'Visible to managers and admins only',
      visibilityRules: [{ type: 'role', operator: 'includes', value: ['manager', 'admin'] }],
      permissionRules: [
        { roles: ['manager'], accessLevel: 'readonly' },
        { roles: ['admin'], accessLevel: 'editable' },
      ],
      validationSchema: z.number().min(0, 'Salary must be positive').optional(),
      transform: (value) => (value ? parseFloat(value as string) : undefined),
    },
    {
      id: 'ssn',
      label: 'Social Security Number',
      type: 'text',
      placeholder: 'XXX-XX-XXXX',
      description: 'Admin only — highly sensitive',
      visibilityRules: [{ type: 'role', operator: 'equals', value: 'admin' }],
      permissionRules: [{ roles: ['admin'], accessLevel: 'editable' }],
      validationSchema: z.string().regex(/^\d{3}-\d{2}-\d{4}$/, 'Invalid SSN format').optional(),
      sanitize: (value) => (typeof value === 'string' ? value.replace(/[^\d-]/g, '') : value),
    },
    {
      id: 'startDate',
      label: 'Start Date',
      type: 'date',
      required: true,
      permissionRules: [
        { roles: ['employee'], accessLevel: 'readonly' },
        { roles: ['manager'], accessLevel: 'readonly' },
        { roles: ['admin'], accessLevel: 'editable' },
      ],
      validationSchema: z.string().optional(),
    },
    {
      id: 'isActive',
      label: 'Active Employee',
      type: 'checkbox',
      defaultValue: true,
      description: 'Admin can deactivate accounts',
      permissionRules: [
        { roles: ['employee', 'manager'], accessLevel: 'readonly' },
        { roles: ['admin'], accessLevel: 'editable' },
      ],
    },
    {
      id: 'notes',
      label: 'Internal Notes',
      type: 'textarea',
      placeholder: 'Manager and admin notes...',
      description: 'Not visible to employees',
      visibilityRules: [{ type: 'role', operator: 'includes', value: ['manager', 'admin'] }],
      permissionRules: [{ roles: ['manager', 'admin'], accessLevel: 'editable' }],
      validationSchema: z.string().optional(),
    },
  ],
};
